# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee930241e4471e748536adc252678a518bc85e942cb28c6d6a6a574fdf2e4e2c615b4fd7a514e1db59ff7c92731b3ce5f7e6d516b0fc56b98df2e482b6f50af6

test:
  secret_key_base: d22be889adbbb6bff21999ff2135c44c71d45ed921bccd53ddc735c81e884850cd926853c8bff49fc9a596c03309cb0bdf6068d76eccd96705a29e41c13ea3eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
